version: '3.2'
services:
  s3:
    image: minio/minio:latest
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    command: 
      server /date
    volumes:
      - ./s3:/date

  db:
      restart: always
      image: linuxserver/mariadb
      ports:
          - "3306:3306"
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - max_allowed_packet=1073741824
      volumes:
          - ./dbdata:/var/lib/mysql

  mlflow:
      image: mlflow:latest
      build:
          context: .
          dockerfile: Dockerfile
      ports:
          - "5000:5000"
      environment: 
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - AWS_DEFAULT_REGION=${AWS_REGION}
          - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
          - CONNECT_STR=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
          #- CONNECT_STR=/asd
          - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
          - DB_HOST=db:3306
      volumes:
          - ./asd:/asd