FROM continuumio/miniconda3:latest

EXPOSE 5000

ADD . /app
WORKDIR /app

COPY wait-for-it.sh wait-for-it.sh 
RUN chmod +x wait-for-it.sh

RUN pip install mlflow boto3 pymysql

ENTRYPOINT ["./wait-for-it.sh", ${DB_URL}, "-t 90", "-- mlflow" ]
CMD ["server", "--backend-store-uri ${CONNECT_STR}", "--default-artifact-root s3://${AWS_BUCKET_NAME}/", "-h 0.0.0.0"]
